title: Arawn Davies Portal
description: The melting pot of software, hardware and experience
author: "Arawn Davies"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
twitter_username: squidwhere
github_username: Arawn-Davies
linkedin_username: arawn-davies
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  skin: dark
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - blog.md
  - projects.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - _upstr
