title: Arawn Davies
author: 
    name: Arawn Davies
    email: arawn@arawn-davies.co.uk
description: >-
    The melting pot of software, hardware and experience
baseurl: /
url: "https://arawn-davies.github.io"
github_username: Arawn-Davies

# Build settings
remote-theme: minima

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Arawn-Davies" }

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Minima: custom header links
header_pages:
  - index.md
  - _pages/about.md
  - _pages/hiring.md
  - _pages/blog.md
  - projects/projects.md

include:
    - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

rss: rss