title: Arawn Davies
email: ""
description: >-
  Graduate of Cyber Security MSc and Computer Science BSc Hons at De Montfort University
  and technical specialist. Writing about security, systems programming, retro computing,
  and my open-source projects.
baseurl: ""
url: "https://arawn-davies.github.io"
github_username: Arawn-Davies

theme: minima

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Arawn-Davies" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
